### ISSUE TITLE
Rightfield 0.24 on a mac is not showing rdfs:label for OWL ontologies?

### ISSUE THREAD

**Issue by ddooley** [myGrid/RightField#11]
I have opened 4 ontologies, including OBI, and all are just showing the ids in the tree view, not the rdfs:labels.

Is there a way to get it to show rdfs:label ?

Thanks for any info.

**Comment by stuzart** [comment]
We've had somebody else mention this and am looking into it. It is probably related to a fix for #9

**Comment by stuzart** [comment]
This has now been fixed, and new downloads are available at https://rightfield.org.uk/download.html
