### ISSUE TITLE
Old version download on rightfield.org.uk

### ISSUE THREAD

**Issue by esthervanenckevort** [myGrid/RightField#3]
The build available as download on rightfield.org.uk is really old and doesn't run on modern Mac systems without installing a deprecated Java version. A while ago I contributed an update to the Rightfield build process to make it possible to run Rightfield with a modern Oracle Java build. This build is not yet available as download.

**Comment by malcook** [comment]
@djvanenckevort  - thanks for the heads up - we're running into this issue - can you share your update out of band?  We'd like to build RightField on a newer Mac too!

**Comment by stuzart** [comment]
@alaninmcr  is currently looking into this, and we hope to have a fresh build available soon as a high priority, followed by an overall refresh of RightField and incorporating some new work that has recently been done.

In the meantime, on a Mac it is possible to download and run the Linux version from the .sh file
