### ISSUE TITLE
RightField corrupts Excel tables

### ISSUE THREAD

**Issue by saharhas** [myGrid/RightField#8]
Excel workbooks containing tables with dynamic named range get corrupted if they have any RightField’ed cells.

Steps to reproduce in Excel 2016:

- Make a blank Excel workbook.
- Fill out cells A1:A3 with the following texts: “SampleList”, ”Sample 1” and ”Sample 2”.
- Turn the sample data into a Table: Select A1:A3 > Insert > Tables > Table (check "My table has headers")
- Give the Table a name: Table Tools > Design > Table name > change the default name "Table1" to "Samples"
- Create a dynamic named range for the Table column: Formulas > Define Name > set "Name" to "SampleList" and "Refers to" to "=Samples[SampleList]" 
- Save the workbook as` SampleTest.xlsx`.
- In RightField, open `SampleTest.xlsx` and JERMOntology
- Add an ontology property to cell B1 (e.g. assay subclasses)
- Saving the workbook will give the following error message:

> An Unexpected FormulaParseException error occurred: Specified named range 'Samples' does not exist in the current workbook.

A similar error will happen if the RightField'ed cell was generated before adding table to the workbook.

**Comment by stuzart** [comment]
I think this will have been fixed through a fix to #7 - the symptoms behind the scenes are the same.
